Implemented HW "Contacts + Server" using jQuery. Added a modal window…
AkintsevaElizaveta/Front-end-PRO pull request #14
Opened 2022-08-14 12:52 UTC by AkintsevaElizaveta

… and the ability to edit the contact.

2022-08-14 16:34 UTC, OleksandrMovchan commented on 21 - contacts + JQuery/main.js
> +                debugger
please remove debugger from here

2022-08-14 16:34 UTC, OleksandrMovchan commented on 21 - contacts + JQuery/main.js
> +            if (contact.id) {
please add blank space between different parts of logic

2022-08-15 08:22 UTC, volodymyr-kryvoshapov commented on 21 - contacts + JQuery/Contacts.js
> +    };
Хороша Ідея, молодець!

2022-08-15 08:32 UTC, volodymyr-kryvoshapov requested changes

2022-08-15 08:32 UTC, volodymyr-kryvoshapov commented on 21 - contacts + JQuery/main.js
> +            if(!validateEmpty(contact.name) || !validateEmpty(contact.lastName) || !validateEmpty(contact.telephone)){
Ось цю всю строку краще винести в окрему функцію: validateContact() або isContactValid()

2022-08-15 08:32 UTC, volodymyr-kryvoshapov commented on 21 - contacts + JQuery/main.js
> +    const html = list.map(generateHtml).join('');
З jquery пам'ятаємо що метод append може приймати массив HTML об'єктів тому .join() тобі не потрібен, дивись https://api.jquery.com/append/#append-content-content

2022-08-15 11:24 UTC, volodymyr-kryvoshapov approved these changes

2022-08-15 11:29 UTC, merged